name: CI/CD

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.x'
          
      - name: Install dependencies
        run: dotnet restore
        
      - name: Build and test
        run: dotnet build --configuration Release && dotnet test --no-build --configuration Release
      
      - name: Publish artifact
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: ./bin/Release/net7.0/publish/
          
  deploy:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: app
          path: .
          
      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          sudo pip3 install awscli
      
      - name: Deploy to AWS Lambda
        run: |
          aws lambda update-function-code --function-name MinhaPrimeiraAPIServerless --zip-file fileb://app.zip